### ISSUE TITLE
Cell orientation problem with some 3D point sets

### ISSUE THREAD

**Issue by tomka** [mikolalysenko/delaunay-triangulate#2]
These two point sets of each five points in 3D space differ only by one component (`x` in fouth coordinate) and are triangulated correctly into two tetrahedra. However, the second one (`points2`) seems to have a strange orientation:

```
var points1 = [ [0, 0, 0], [2, 0, 0], [2, 1, 0], [2, 0, 1], [4, 0, 0] ];
var points2 = [ [0, 0, 0], [2, 0, 0], [2, 1, 0], [1, 0, 1], [4, 0, 0] ];
```

The two `delaunay-triangulate` generated tetrahedra are:

```
var simplices1 = [ [3, 2, 1, 4], [2, 0, 3, 1] ];
var simplices2 = [ [3, 2, 1, 4], [3, 2, 0, 1] ];
```

Oddly `cell-orientation` returns the same orientation for all three result simplices (`-1`), but somehow they still seem to differ---at least looking at the 2-skeletons shows that the resulting triangles are clearly oriented differently:

```
var k2simplices1 = [ [2, 0, 1], [0, 3, 1], [2, 0, 3], [2, 3, 1] ];
var k2simplices2 = [ [2, 0, 1], [3, 0, 1], [3, 2, 0], [3, 2, 1] ];
```

Is this a bug or expected? This behavior is unfortunate, because boundary calculation (e.g. in `simplicial-complex` and `simplicial-complex-boundary`) and `reduce-simplicial-complex` don't work on the the simplices having a different orientation (they expect the same orientation). Additionally, visualization becomes problematic, since normals can't be easily calculated anymore (because orientation isn't consistent). If this is expected, is there already a way to unify orientation across all simplices?

**Comment by mikolalysenko** [comment]
Oh shit!  I think this is a bug in simplicial-complex-boundary.  Looking at the definition from simplicial homology, we should be flipping the orientation of every other cell.  I'll take a look at it ASAP, should be a quick fix:

https://en.wikipedia.org/wiki/Singular_homology#Singular_simplices

**Comment by tomka** [comment]
Awesome, I looked also a little bit more into this and can confirm that `boundary-cells` is the problem. I used a modified version where I flip every other boundary cell, which fixed the issue for my 3D triangulation Of course it would be great to have this fixed in the module, thanks!

**Comment by mikolalysenko** [comment]
Alright, I just pushed a new version which should fix the problem in boundary-cells.

**Comment by mikolalysenko** [comment]
Funny that the way I wrote it the bug only showed up for even dimensional cells in d >= 4 (so tetrahedra were the first broken example).

**Comment by tomka** [comment]
Thanks for fixing this so quickly. I just tested the new `boundary-cells` module and now everything works like a charm and I think this issue can be closed again! The example point sets above now produce the same simplices.

With this working, I can go back to implementing interval based alpha shapes (get two alpha-ranges per simplex: regular- and interior, makes finding the right alpha easier/quicker). :-)
